- name: Install git
  apt:
    pkg: git
    state: present
  sudo: yes

- name: Create app directory
  file:
    path: /opt/app
    owner: ubuntu
    group: ubuntu
    state: directory
  sudo: yes

- name: Clone repository
  git:
    repo: "https://github.com/marciaga/ansible_nextjs.git"
    dest: /opt/app
    version: master

- name: Install upstart script
  copy:
    src: upstart.conf
    dest: /etc/upstart/app.conf
  sudo: yes

- name: Enable and start the application
  service:
    name: app
    enabled: yes
    state: restarted
  sudo: yes
