- name: Install git
  apt:
    pkg: git
    state: present
  become: true

- name: Create app directory
  file:
    path: /opt/app
    owner: ubuntu
    group: ubuntu
    state: directory
  become: true

- name: Clone repository
  git:
    repo: "https://github.com/marciaga/ansible_nextjs.git"
    dest: /opt/app
    version: master

- name: Prep Yarn install
  shell: >
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - &&
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - &&
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- name: Install Node, npm, and Yarn
  become: true
  apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - build-essential
    - nodejs
    - yarn

- name: Install n
  npm: name=n global=yes
  become: true

- name: Change Node version
  command: n 6.9.1
  become: true

- name: Install pm2
  npm: name=pm2 global=yes
  become: true

- name: Install Dependencies
  command: yarn
  args:
    chdir: /opt/app

- name: Build Application
  command: yarn build
  args:
    chdir: /opt/app

- name: Start Application
  command: pm2 start npm --name app --env production -- start
  args:
    chdir: /opt/app
