- name: Install Nginx
  apt:
    pkg: nginx
    state: present
  become: true

- name: Configure Nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/default
  become: true

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
  become: true
